---
# tasks file for mysql-db
- name: Create VM
    azure_rm_virtualmachine:
    resource_group: boggs-rg-ncus
    name: assign-db01
    vm_size: Standard_B1ms
    admin_username: smaug
    admin_password: "{{ vm_password }}"
    network_interfaces: assign-db-nic
    os_type: Linux
    image:
        offer: CentOS
        publisher: OpenLogic
        sku: 8_2
        version: latest
- name: Install MariaDB database
  apt: 
    name: ['mariadb-server', 'mariadb-client']
    state: present
- name: Start MariaDB service
  service: 
    name: mariadb
    enabled: true
    state: started
- name: Create application database
  mysql_db: 
    name: "{{ db_name }}"
    state: present
- name: Create database user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL'
    state: present
    host: '%'